#!/usr/bin/env bash

local_cache_file="$HOME/.cache/tmux-sessionizer-dirs.cache"
UPDATE=false

if [[ $# -eq 1 ]] && [[ "$1" == "--update" ]]; then
  UPDATE=true
elif [[ $# -eq 1 ]]; then
  selected=$1
fi

if [[ -z "$selected" ]]; then
  gdrive_cache_file="$HOME/.cache/gdrive.cache"

  # Use cached local dirs if fresh (< 60 min), otherwise recompute and save
  if [[ "$UPDATE" == false ]] && find "$local_cache_file" -mmin -60 -type f 2>/dev/null | grep -q .; then
    local_dirs=$(<"$local_cache_file")
  else
    dot_dir=$(find "$HOME/.dotfiles" -mindepth 0 -maxdepth 0 -type d 2>/dev/null)
    todo_dir=$(find "$HOME/.dotfiles/.config/todo" -mindepth 0 -maxdepth 0 -type d 2>/dev/null)
    git_dirs=$(find "$HOME/Documents/01-Git" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)
    other_git_dirs=$(find "$HOME/Documents/01-Git" -mindepth 2 -maxdepth 2 -type d -regex '.*/[0-9]\{2\}-[^/]*$' 2>/dev/null)
    doc_dirs=$(find "$HOME/Documents" -mindepth 1 -maxdepth 1 -type d 2>/dev/null)
    local_dirs=$(echo -e "$dot_dir\n$todo_dir\n$doc_dirs\n$git_dirs\n$other_git_dirs")
    echo "$local_dirs" >"$local_cache_file"
  fi

  OS_TYPE=$(uname)

  if [[ "$OS_TYPE" == "Darwin" ]]; then

    gdrive_account_file="$HOME/.gdrive_account"

    if [ -f "$gdrive_account_file" ]; then
      chosen_directory=$(<"$gdrive_account_file")
    else

      directories=()

      base_directory="/Users/$USER/Library/CloudStorage"
      while IFS= read -r -d '' dir; do
        directories+=("$dir")
      done < <(find "$base_directory" -type d -not -name ".*" -print0 -mindepth 1 -maxdepth 1)

      if [ ${#directories[@]} -gt 1 ]; then
        echo "Multiple directories found. Please choose one:"
        select chosen_directory in "${directories[@]}"; do
          if [ -n "$chosen_directory" ]; then
            echo "You chose: $chosen_directory"
            break
          else
            echo "Invalid choice. Please try again."
          fi
        done
      else
        if [ ${#directories[@]} -eq 1 ]; then
          chosen_directory="${directories[0]}"
        fi
      fi

      chosen_directory=$(echo -e "$chosen_directory/My Drive")
      echo "$chosen_directory" >"$gdrive_account_file"
    fi

    drive_dirs=$(find $chosen_directory -mindepth 1 -maxdepth 6 -type d -regex '^[ a-zA-Z/]*\(\/[0-9][0-9]-[^/]*\)+[^/]+$' 2>/dev/null)

  elif [[ "$OS_TYPE" == "Linux" ]]; then
    chosen_directory="$HOME/GDrive"

    if [[ "$UPDATE" == true ]]; then
      # Synchronously refresh gdrive cache
      drive_dirs=""
      if systemctl --user is-active --quiet rclone@GDrive; then
        drive_dirs=$(find $chosen_directory -mindepth 1 -maxdepth 6 -type d -regex '^[ a-zA-Z/]*\(\/[0-9][0-9]-[^/]*\)+[^/]+$' 2>/dev/null)
        echo "$drive_dirs" >"$gdrive_cache_file"
      fi
    else
      if [[ -f "$gdrive_cache_file" ]]; then
        drive_dirs=$(<"$gdrive_cache_file")
      else
        drive_dirs=""
      fi

      # Start background caching
      (
        sleep 1
        if [[ ! -f /tmp/gdrive ]] && systemctl --user is-active --quiet rclone@GDrive; then
          touch /tmp/gdrive.cache
          find $chosen_directory -mindepth 1 -maxdepth 6 -type d -regex '^[ a-zA-Z/]*\(\/[0-9][0-9]-[^/]*\)+[^/]+$' >/tmp/gdrive.cache 2>/dev/null
          mv /tmp/gdrive.cache $gdrive_cache_file
        fi
      ) &
    fi

  fi

  # Directories with an already-open tmux session float to the top.
  # Session names are basename(dir) with dots turned into underscores (see below).
  open_sessions=$(tmux list-sessions -F '#{session_name}' 2>/dev/null)

  selected=$(echo -e "$local_dirs\n$drive_dirs" | awk '!seen[$0]++' | grep -E '.+' \
    | awk -v sessions="$open_sessions" '
        BEGIN { n = split(sessions, a, "\n"); for (i = 1; i <= n; i++) open[a[i]] = 1 }
        {
          name = $0
          sub(/\/+$/, "", name)
          sub(/.*\//, "", name)
          gsub(/\./, "_", name)
          print ((name in open) ? "0\t" : "1\t") $0
        }' \
    | sort -s -k1,1 -t $'\t' | cut -f2- | fzf -i)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# Problems with rclone
# if [[ ! -d "$selected" ]]; then
#   exit 1
# fi

if command -v zoxide &>/dev/null; then
  zoxide add "$selected"
fi

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s "$selected_name" -c "$selected" &>/dev/null
  exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
  tmux new-session -ds "$selected_name" -c "$selected" &>/dev/null
fi

tmux switch-client -t "$selected_name" &>/dev/null
tmux attach-session -t "$selected_name" &>/dev/null

